# Generated by Django 4.1 on 2023-01-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('repository', models.CharField(max_length=300)),
                ('git_page', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='img_proyect')),
            ],
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
