# Generated by Django 4.1 on 2023-02-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_project_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img_proyect'),
        ),
        migrations.DeleteModel(
            name='image',
        ),
    ]
