# Generated by Django 4.1 on 2023-01-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_project_delete_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='textoooo', max_length=300),
        ),
    ]
