# Generated by Django 4.1 on 2023-02-13 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_project_image_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img_proyect')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.project')),
            ],
        ),
    ]
